wrinklr_app/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from wrinklr_app import views

urlpatterns = [
    url(r'^$', views.input_celebs, name='input_celebs'),
    url(r'^age$', views.age, name='age'),
    url(r'^vs/(?P<matchup_id>[0-9]+)$', views.matchup, name='matchup'),
    url(r'^vs/(?P<matchup_id>[0-9]+)/results$', views.matchup_results, name='matchup_results'),
    url(r'^navbar_login$', views.navbar_login, name='navbar_login'),
    url(r'^login$', 
        login, 
        name='login', 
        kwargs={
            'redirect_authenticated_user': True,
            'template_name': 'wrinklr_app/login.html',
            'extra_context': {'navbar_text': 'Login'}
        }),
    url(r'^logout$', logout, name='logout', kwargs={'next_page': '/wrinklr/'}),
    url(r'^register$', views.register, name='register'),
    url(r'^slack/slash$', views.slack_slash, name='slack_slash'),
    url(r'^slack/action$', views.slack_action, name='slack_action'),
    url(r'^ping$', views.ping, name='ping')
]

wrinklr_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from wrinklr_django import views

admin.autodiscover()

urlpatterns = [ 
    # Examples:
    # url(r'^$', 'wrinklr_django.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.home),
    url(r'^wrinklr/', include('wrinklr_app.urls', namespace='wrinklr_app'), name='wrinklr'),
    url(r'^admin/', include(admin.site.urls)),
]

wrinklr_app/models.py
import logging
import datetime

from django.db import models
from django.core.validators import validate_comma_separated_integer_list
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.exceptions import ObjectDoesNotExist

from .celeb_age import get_bday
from .celeb_age import get_wiki_name_path
from .celeb_age import NoPersonDataException, NoWikiEntryException, NoBirthdayException

logger = logging.getLogger('wrinklr')

def validate_birth_date(value):
    usage = 'provide three ints in form "year,month,day"'
    tokens = value.split(',')
    if len(tokens) != 3:
        raise ValidationError(usage)

    try:
        for t in tokens:
            int(t) 
    except ValueError:
        raise ValidationError(usage)


class Person(models.Model):
    name = models.CharField(max_length = 200)
    birth_date = models.CharField(default = '', max_length = 20, validators=[validate_birth_date])
    date_updated = models.DateField(auto_now = True)
    date_created = models.DateField(auto_now_add = True)


    def _age_in_days(self):
        birth_date = Person.birth_date_to_list(self.birth_date)
        now = self._now()
        return self._n_days(now) - self._n_days(birth_date)

    def _age_str(self):
        birth_date = Person.birth_date_to_list(self.birth_date)
        return str(int(self.age_in_days/365)) + ' years old (born ' +  Person.birth_date_to_formatted_str(birth_date) + ')'

    # Derived properties
    age_in_days = property(_age_in_days)
    age_str = property(_age_str)

    @staticmethod
    def _now():
        now = datetime.datetime.utcnow().date()
        return (now.year, now.month, now.day)

    @staticmethod
    def _n_days(date):
        year, month, day = date
        factor = -1 if year < 0 else 1
        return factor * (abs(year) * 365 + month * 30 + day)
    
    @staticmethod
    def birth_date_to_str(birth_date):
        return ','.join(map(str, birth_date))

    @staticmethod
    def birth_date_to_formatted_str(birth_date):
        return '/'.join(map(str, [birth_date[1], birth_date[2], birth_date[0]]))

    @staticmethod
    def birth_date_to_list(birth_date):
        return [int(x) for x in birth_date.split(',')]

    # This should be used instead of Person() constructor.
    # It will properly format the 'name' field
    @staticmethod
    def init(**kwargs):
        name = kwargs.get('name')
        if name:
            kwargs['name'] = Person.format_name(name)
        return Person(**kwargs)

    @staticmethod
    def format_name(name):
        return get_wiki_name_path(name, " ")

    @staticmethod
    def get_or_create(name):
        person = None
        try:
            #Try to get from db
            name = Person.format_name(name)
            person = Person.objects.get(name=name)
        except ObjectDoesNotExist:
            #create from wikipedia
            person = Person.create_from_wiki(name)
        return person

    @staticmethod
    def create_from_wiki(name):
        try:
            birth_date = get_bday(name)
        except (NoPersonDataException, NoWikiEntryException, NoBirthdayException):
            logger.warn("Could not find wikipedia page for '%s'", name)
            return None

        person = Person(
            name = Person.format_name(name),
            birth_date = Person.birth_date_to_str(birth_date)
        )

        try:
            person.full_clean()
        except ValidationError:
            logger.warn("Could not validate %s", person)
            return None

        #TODO: error handling in save
        person.save()
        return person

    def __str__(self):
        return repr(self)

    def __repr__(self):
        return ', '.join(['Name: ' + self.name,
                          'Birthday: ' + self.birth_date,
                          'Updated: ' + repr(self.date_updated),
                          'Created: ' + repr(self.date_created)])

class Matchup(models.Model):
    person1 = models.ForeignKey(Person, models.PROTECT, related_name='person1')
    person2 = models.ForeignKey(Person, models.PROTECT, related_name='person2')
    creator = models.ForeignKey(User, models.PROTECT)
    date_updated = models.DateField(auto_now = True)
    date_created = models.DateField(auto_now_add = True)

    def _older(self):
        if self.person1.age_in_days > self.person2.age_in_days:
            return self.person1
        else:
            return self.person2

    # Derived properties
    older = property(_older)

    class Meta:
        unique_together = ('person1', 'person2')

    @staticmethod
    def get_or_create(person1, person2, creator):
        def get(p1, p2):
            try:
                matchup = Matchup.objects.get(person1=p1, person2=p2)
            except Matchup.DoesNotExist:
                matchup = None
            return matchup

        matchup = get(person1, person2)
        if not matchup:
            matchup = get(person2, person1)

        if not matchup:
            matchup = Matchup(person1=person1, person2=person2, creator=creator)
            matchup.full_clean()
            matchup.save()

        return matchup

    def __str__(self):
        return repr(self)

    def __repr__(self):
        return ', '.join(['Person1: ' + self.person1.name,
                          'Person2: ' + self.person2.name,
                          'Creator: ' + self.creator.username,
                          'Updated: ' + repr(self.date_updated),
                          'Created: ' + repr(self.date_created)])

class MatchupGuess(models.Model):
    matchup = models.ForeignKey(Matchup, models.PROTECT)
    user = models.ForeignKey(User, models.PROTECT)
    guess = models.ForeignKey(Person, models.PROTECT)
    result = models.BooleanField(default = False)
    date_updated = models.DateField(auto_now = True)
    date_created = models.DateField(auto_now_add = True)

    def _result_str(self):
        if self.matchup.older.id == self.guess.id:
            return 'Correct, %s is older.' % self.guess.name
        else:
            return 'Incorrect, %s is younger.' % self.guess.name


    # derived properties
    result_str = property(_result_str)
    property

    class Meta:
        unique_together = ('matchup', 'user')

    @staticmethod
    def create_guess(person, matchup, user):
        correct = matchup.older.id == person.id
        guess = MatchupGuess(matchup=matchup, 
                             user=user,
                             guess=person,
                             result=correct)

        guess.full_clean()
        guess.save()
        return guess

    def __str__(self):
        return repr(self)

    def __repr__(self):
        return ', '.join(['Person1: ' + self.matchup.person1.name,
                          'Person2: ' + self.matchup.person2.name,
                          'Guess: '   + self.guess.name,
                          'User: '    + self.user.username,
                          'Updated: ' + repr(self.date_updated),
                          'Created: ' + repr(self.date_created)])

wrinklr_app/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.conf import settings
from wrinklr_app import slack

import json
import logging

from .models import Person
from .models import Matchup
from .models import MatchupGuess

logger = logging.getLogger('wrinklr')
_client = slack.Client(settings.SLACK_OATH_TOKEN)

def input_celebs(request):
    if request.method == 'POST':
        return input_celebs_post(request)
    elif request.method == 'GET':
        return input_celebs_render(request)

@login_required
def input_celebs_post(request):
    name1, name2 = request.POST['person1'], request.POST['person2']
    person1, person2 = Person.get_or_create(name1), Person.get_or_create(name2)

    if not person1 or not person2:
        def create_dict(n, p):
            return {'name': n, 'valid': bool(p)}

        return input_celebs_render(request,
                                   person1=create_dict(name1, person1), 
                                   person2=create_dict(name2, person2))

    else:
        matchup = Matchup.get_or_create(person1=person1, 
                                        person2=person2, 
                                        creator=request.user)
        return redirect('wrinklr_app:matchup', matchup_id=matchup.id)

def input_celebs_render(request, person1=None, person2=None):
        guesses = []
        if not request.user.is_anonymous():
            guesses = MatchupGuess.objects.filter(user=request.user)
        open_matchups = Matchup.objects.exclude(id__in=[x.matchup.id for x in guesses])

        context = {
            'guesses': guesses,
            'open_matchups': open_matchups,
            'person1': person1,
            'person2': person2
        }

        return render(request, 'wrinklr_app/input_celebs.html', context)


def age(request):
    if 'name' in request.GET:
        person = Person.create_from_wiki(request.GET['name'])

    if not person:
        person = Person.init(name='Error')

    context = {
        'person': person
    }
    return render(request, 'wrinklr_app/age.html', context)

def matchup(request, matchup_id):
    if request.method == 'POST':
        return matchup_post(request, matchup_id)

    elif request.method == 'GET':
        matchup = get_object_or_404(Matchup, id=matchup_id)

        user_guess = None
        if not request.user.is_anonymous():
            user_guess = MatchupGuess.objects.filter(matchup=matchup, user=request.user)

        if user_guess:
            return redirect('wrinklr_app:matchup_results', matchup_id=matchup_id)
        else:
            context = { 
                'matchup': matchup
            }
            return render(request, 'wrinklr_app/matchup.html', context)

@login_required
def matchup_post(request, matchup_id):
    person = Person.objects.get(id=request.POST['guess_person_id'])
    matchup = Matchup.objects.get(id=matchup_id)
    MatchupGuess.create_guess(person, matchup, request.user)

    return redirect('wrinklr_app:matchup_results', matchup_id=matchup.id)

@login_required
def matchup_results(request, matchup_id):
    matchup = get_object_or_404(Matchup, id=matchup_id)
    guesses = MatchupGuess.objects.filter(matchup=matchup)
    user_guess = guesses.filter(user=request.user)

    if not user_guess:
        return redirect('wrinklr_app:matchup', matchup_id=matchup_id)
    else:
        context = {
            'user_guess': user_guess[0],
            'matchup': matchup,
            'guesses': guesses
        }
        return render(request, 'wrinklr_app/matchup_results.html', context)


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password1']
        user = User.objects.create_user(username=username, password=password)
        login(request, user)
        return redirect('wrinklr_app:input_celebs')

    elif request.method == 'GET':
        context = {
            'form': UserCreationForm(),
            'navbar_text': 'Register'
        }
        return render(request, 'wrinklr_app/register.html', context)

def navbar_login(request):
    if request.method == 'GET':
        if 'login' in request.GET:
            return redirect('wrinklr_app:login')
        elif 'register' in request.GET:
            return redirect('wrinklr_app:register')
        elif 'logout' in request.GET:
            return redirect('wrinklr_app:logout')

@csrf_exempt
def slack_slash(request):
    if request.method == 'POST':
        logger.info(request.POST)
        text = request.POST['text']
        response_url = request.POST['response_url']
        username = request.POST['user_name']

        name1, name2 = slack.parse_slash_command(text) 

        if not name1 or not name2:
            response = slack.form_parse_error(text)
        else:
            person1 = Person.get_or_create(name1)
            person2 = Person.get_or_create(name2)

            err_names = []
            if not person1: err_names.append(name1)
            if not person2: err_names.append(name2)

            if err_names:
                response = slack.form_error_response(err_names)
            else:
                # Make slack user in case it doesn't exist
                user = User.objects.get_or_create(username='slack')[0]

                matchup = Matchup.get_or_create(person1=person1, 
                                                person2=person2, 
                                                creator=user)
                footer = 'Created by %s.' % username
                response = slack.form_slash_response(matchup, '', footer)

        slack.respond_to_url(response_url, response)

        return HttpResponse()

@csrf_exempt
def slack_action(request):
    if request.method == 'POST':
        logger.info(request.POST)
        payload = json.loads(request.POST['payload'])

        response_url = payload['response_url']
        callback_id = payload['callback_id']
        channel_id = payload['channel']['id']
        message_ts = payload['message_ts']
        original_msg = payload['original_message']
        thread_ts = original_msg.get('thread_ts')
        user = payload['user']['name']
        person_id = payload['actions'][0]['value']
        
        matchup_id = slack.parse_callback_id(callback_id)
        matchup = Matchup.objects.get(id=matchup_id)
        guess = Person.objects.get(id=person_id)

        results = slack.update_results(original_msg, user, guess, matchup)
        footer = original_msg['attachments'][2]['footer']
        spoiler = ' Spoilers in thread below.'
        if spoiler not in footer:
            footer += spoiler

        if results:
            response = slack.form_slash_response(matchup, results, footer)
            slack.respond_to_url(response_url, response)

            if not thread_ts:
                # First response, add the solution
                text = slack.get_solution_text(matchup)
                _client.send_thread_message(text, channel_id, message_ts)

    return HttpResponse()

def ping(request):
    return HttpResponse()

wrinklr_app/templates/wrinklr_app/age.html
{{ person.name }} {{ person.birth_date}}

wrinklr_app/templates/wrinklr_app/base.html
{% load staticfiles %}

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" 
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" 
          crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" 
            crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'wrinklr_app/wrinklr.css' %}">
    <title>Wrinklr</title>

  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container-fluid">
        <!-- left navbar --!>
        <div class="navbar-header">
          <a class="navbar-brand" href={% url "wrinklr_app:input_celebs" %}>Wrinklr</a>
          <p class="navbar-text">{{ navbar_text }}</p>
        </div>

        <!-- right navbar --!>
        <div class="navbar-right">
          {% if not user.is_anonymous %}
          <p class="navbar-text">Welcome, {{ user.username }}</p>
          {% endif %}

          <form class="navbar-form navbar-right" 
                action={% url "wrinklr_app:navbar_login" %} 
                method="GET">
            {% if user.is_anonymous %}
            <button type="submit" 
                    name="login" 
                    class="btn btn-success">Sign in</button>
            <button type="submit" 
                    name="register" 
                    class="btn btn-success">Sign up</button>
            {% else %}
            <button type="submit" 
                    name="logout" 
                    class="btn btn-success">Logout</button>
            {% endif %}
          </form>
        </div>

      </div>
    </nav>

    {% block content %}
    {% endblock %}

  </body>
</html>

wrinklr_app/templates/wrinklr_app/image_search.html
{% extends "wrinklr_app/base.html" %}
{% block content %}

{% load static %}

<img src={{ image_url }}>

{% endblock %}

wrinklr_app/templates/wrinklr_app/input_celebs.html
{% extends "wrinklr_app/base.html" %}
{% block content %}

<form action={% url "wrinklr_app:input_celebs" %} method="POST">
    {% csrf_token %}
    Person 1:<br>
    <input type="text" name="person1" value="{{ person1.name }}">
    {% if person1 and not person1.valid %}
    Whoops, could not find person!
    {% endif %}
    <br>
    Person 2:<br>
    <input type="text" name="person2" value="{{ person2.name }}">
    
    {% if person2 and not person2.valid %}
    Whoops, could not find person!
    {% endif %}

    <br><br>
    <input type="submit" value="Submit">
</form>

<h3>Open matchups</h3>
<ul>
{% for matchup in open_matchups %}
<li>
    <a href={% url "wrinklr_app:matchup" matchup.id %}>
        {{ matchup.person1.name }} vs {{ matchup.person2.name }}
    </a>
</li>
{% endfor %}  
</ul>


{% if not user.is_anonymous %}
<h3>Your guesses</h3>
<ul class='blah'>
{% for guess in guesses %}
<li>
    <a href={% url "wrinklr_app:matchup" guess.matchup.id %}>
        {% if guess.result %} &#x2713; {% else %} &#x2717; {% endif %}
        {{ guess.matchup.person1.name }} vs {{ guess.matchup.person2.name }}
    </a>
</li>
{% endfor %}  
{% endif %}
</ul>

{% endblock %}

wrinklr_app/templates/wrinklr_app/login.html
{% extends "wrinklr_app/base.html" %}
{% block content %}

{% if form.errors %}
<p>Could not login user. Please try again</p>
{% endif %}

<form method="post" action={% url "wrinklr_app:login" %}>
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

wrinklr_app/templates/wrinklr_app/matchup.html
{% extends "wrinklr_app/base.html" %}
{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href={% static "wrinklr_app/matchup.css" %} />

{% if user.is_anonymous %}

Who is older, {{ matchup.person1.name }} or {{ matchup.person2.name }}?
<br>
Login to vote!

{% else %}

Who is older?
<br>
<form action={% url "wrinklr_app:matchup" matchup.id %} method="POST">
    {% csrf_token %}
    <input type="radio" name="guess_person_id" value={{ matchup.person1.id }} checked> {{ matchup.person1.name }}<br>
    <input type="radio" name="guess_person_id" value={{ matchup.person2.id }}> {{ matchup.person2.name }}<br>
    <input type="submit" value="Submit!">
</form>

{% endif %}

<br><br><br><br><br>
Matchup submitted by {{ matchup.creator }} on {{ matchup.date_created }}.

{% endblock %}

wrinklr_app/templates/wrinklr_app/matchup_results.html
{% extends "wrinklr_app/base.html" %}
{% block content %}

{{ matchup.person1.name }} {{ matchup.person1.age_str }} <br>
{{ matchup.person2.name }} {{ matchup.person2.age_str }} <br>
<b>{{ user_guess.result_str }}</b>

{% endblock %}

wrinklr_app/templates/wrinklr_app/register.html
{% extends "wrinklr_app/base.html" %}
{% block content %}

{% if form.errors %}
<p>Error creating new user. Please try again.</p>
{% endif %}

<form method="post" action={% url "wrinklr_app:register" %}>
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password1.label_tag }}</td>
    <td>{{ form.password1 }}</td>
</tr>
<tr>
    <td>{{ form.password2.label_tag }}</td>
    <td>{{ form.password2 }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}